version: "3.8"

services:
  model:
    build:
      context: ./model
    ports:
      - "7860:7860"
    environment:
      - MLFLOW_TRACKING_USERNAME=${MLFLOW_TRACKING_USERNAME}
      - MLFLOW_TRACKING_PASSWORD=${MLFLOW_TRACKING_PASSWORD}
    networks:
      - app-network

  ui:
    build:
      context: ./ui
    ports:
      - "8080:8080"
    environment:
      - MODEL_SERVING_URL=${MODEL_SERVING_URL}
    networks:
      - app-network


networks:
  app-network:
    driver: bridge
