name: Model MLFlow CI Pipeline


# Trigger logic
on:
  # Triggered by pushes to the main branch related to notebooks in Model microservice
  push:
    branches:
      - main
    paths:
      - "**.ipynb"
  # Manual trigger for debug
  workflow_dispatch:


# Default work directory
defaults:
  run:
    working-directory: ./model

# CI jobs
jobs:
  # CI Pipeline
  # 1. Executes the MLFlow update model script
  update_model_registry:
    runs-on: ubuntu-latest

    steps:
      # Check out the repository code
      - name: Checkout code
        uses: actions/checkout@v2

      # Set up Python environment
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.11'

      # Install requirements
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # Run the script (requires env variables)
      - name: Run champion model update script
        env:
          MLFLOW_TRACKING_USERNAME: ${{ secrets.MLFLOW_TRACKING_USERNAME }}
          MLFLOW_TRACKING_PASSWORD: ${{ secrets.MLFLOW_TRACKING_PASSWORD }}
        run: |
          python scripts/update_mlflow_model.py
