name: Model CD Pipeline

on:
  registry_package:
    types: [published]

jobs:
  # 1. Deploy Docker image on Render
  deploy:
    runs-on: ubuntu-latest
    if: ${{ (github.event.package.package_type == 'container') && (github.event.package.name == 'matteogianferrari/homelens-ca-model' }}

    steps:
      - name: Trigger Deploy on Render
        run: |
          curl -X POST "${{ secrets.HOMELENS_CA_MODEL_DEPLOY_HOOK }}"
