name: Model CD Pipeline

on:
  registry_package:
    types: [published]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    if: ${{ github.event_name == 'registry_package' && github.event.package.package_type == 'container' && github.event.package.name == github.repository + '-model' }}

    steps:
      - name: Trigger Deploy on Render
        run: |
          curl -X POST "${{ secrets.HOMELENS_CA_MODEL_DEPLOY_HOOK }}"
