name: UI CD Pipeline

on:
  registry_package:
    types: [published]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    if: ${{ github.event_name == 'registry_package' && github.event.package.package_type == 'container' && (github.event.package.name == format('{0}-ui', github.repository))  || github.event_name == 'workflow_dispatch' }}

    steps:
      - name: Trigger Deploy on Render
        run: |
          curl -X POST "${{ secrets.HOMELENS_CA_UI_DEPLOY_HOOK }}"
